version: '3.8'
services:
  dev-database:
    image: postgres:15.0
    container_name: dev-database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abc12345678
      POSTGRES_DB: testdb
    networks:
      - nestjs-network
networks:
  nestjs-network:

#docker compose up -d

#How to remove container+volumes
#docker compose rm dev-database --stop --force --volumes